# Generated by Django 4.1 on 2022-08-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='session_data',
            fields=[
                ('session_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numbers', models.IntegerField()),
                ('serial', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('session_start_time', models.CharField(max_length=15)),
                ('session_end_time', models.CharField(max_length=15)),
                ('session_status', models.BooleanField()),
                ('temp_highest_level', models.FloatField()),
                ('temp_lowest_level', models.FloatField()),
                ('humidity_highest_level', models.FloatField()),
                ('humidity_lowest_level', models.FloatField()),
                ('time_interval', models.TimeField(default='00:00:00')),
            ],
            options={
                'db_table': 'Session_data',
            },
        ),
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature_in_range', models.BooleanField()),
                ('humidity_in_range', models.BooleanField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.session_data', verbose_name='Session_id')),
            ],
            options={
                'db_table': 'Alerts',
            },
        ),
    ]
