# Generated by Django 4.1 on 2022-09-05 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
                ('baud_rate', models.IntegerField()),
                ('parity_bit', models.BooleanField()),
                ('stop_bit', models.BooleanField()),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='drug_template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_temperature', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('max_humidity', models.FloatField()),
                ('min_humidity', models.FloatField()),
            ],
            options={
                'db_table': 'drug_template',
            },
        ),
        migrations.CreateModel(
            name='group_privileges',
            fields=[
                ('group_name', models.AutoField(primary_key=True, serialize=False)),
                ('print_report', models.BooleanField()),
                ('view_time_table', models.BooleanField()),
                ('view_channel_info', models.BooleanField()),
                ('create_user', models.BooleanField()),
                ('delete_user', models.BooleanField()),
                ('create_grp', models.BooleanField()),
                ('delete_grp', models.BooleanField()),
                ('grp_list', models.BooleanField()),
                ('add_session', models.BooleanField()),
                ('delete_session', models.BooleanField()),
            ],
            options={
                'db_table': 'group_privileges',
            },
        ),
        migrations.CreateModel(
            name='probe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField()),
                ('probe_offset', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'probe',
            },
        ),
        migrations.CreateModel(
            name='session_data',
            fields=[
                ('session_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numbers', models.IntegerField()),
                ('serial', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('session_start_time', models.CharField(max_length=15)),
                ('session_end_time', models.CharField(max_length=15)),
                ('session_status', models.BooleanField()),
                ('temp_highest_level', models.FloatField()),
                ('temp_lowest_level', models.FloatField()),
                ('humidity_highest_level', models.FloatField()),
                ('humidity_lowest_level', models.FloatField()),
                ('time_interval', models.TimeField(default=datetime.time(0, 15))),
            ],
            options={
                'db_table': 'Session_data',
            },
        ),
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('session_tokens', models.CharField(max_length=200)),
                ('group_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.group_privileges', verbose_name='group_privileges')),
            ],
            options={
                'db_table': 'userdetails',
            },
        ),
        migrations.CreateModel(
            name='userlogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logs', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.userdetails', verbose_name='userdetails')),
            ],
            options={
                'db_table': 'userlogs',
            },
        ),
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature_in_range', models.BooleanField()),
                ('humidity_in_range', models.BooleanField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.session_data', verbose_name='Session_id')),
            ],
            options={
                'db_table': 'Alerts',
            },
        ),
    ]
